### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by SuavePlan** [supertokens/supertokens-docker-mongodb#3]
I'm trying to get the mongodb module integrated. It works when using the default "in-memory" option, but when using a mongodb url I get the following responses:

when calling http://api.example.com:4000/auth/signup/email/exists?email=myemailaddress%40hotmail.com

I get the following web response:

    Error: SuperTokens core threw an error for a GET request to path: '/recipe/user' with status code: 500 and message: Internal Error

    at Querier.<anonymous> (/Users/wsp/react-website/api-server/node_modules/supertokens-node/lib/build/querier.js:264:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/wsp/react-website/api-server/node_modules/supertokens-node/lib/build/querier.js:22:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

And the logs returned from docker:

    24 Apr 2021 12:32:31:514 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:152) | API called: /recipe/user. Method: GET. Version: 2.7

    24 Apr 2021 12:32:31:519 +0000 | ERROR | pid: 174172de-95ba-4700-8074-c196787f93fa | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | 
    java.lang.UnsupportedOperationException: 
	at io.supertokens.storageLayer.StorageLayer.getEmailPasswordStorage(StorageLayer.java:120)
	at io.supertokens.emailpassword.EmailPassword.getUserUsingEmail(EmailPassword.java:200)
	at io.supertokens.webserver.api.emailpassword.UserAPI.doGet(UserAPI.java:69)
	at io.supertokens.webserver.RecipeRouter.doGet(RecipeRouter.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:159)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)

    24 Apr 2021 12:32:31:519 +0000 | ERROR | pid: 174172de-95ba-4700-8074-c196787f93fa | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:161) | API threw an exception: /recipe/user

    24 Apr 2021 12:32:31:520 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [http-nio-0.0.0.0-3567-exec-5] thread | io.supertokens.webserver.WebserverAPI.service(WebserverAPI.java:180) | API ended: /recipe/user. Method: GET

    24 Apr 2021 12:32:33:756 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [cluster-ClusterId{value='60840f0feee7e9676940005d', description='null'}-mongodb:27017] thread | io.supertokens.storage.mongodb.MongoDBLoggingAppender.doAppend(MongoDBLoggingAppender.java:136) | Checking status of mongodb:27017

    24 Apr 2021 12:32:33:758 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [cluster-ClusterId{value='60840f0feee7e9676940005d', description='null'}-mongodb:27017] thread | io.supertokens.storage.mongodb.MongoDBLoggingAppender.doAppend(MongoDBLoggingAppender.java:136) | Sending command '{"ismaster": 1, "$db": "admin"}' with request id 34 to database admin on connection [connectionId{localValue:1, serverValue:1}] to server mongodb:27017

    24 Apr 2021 12:32:33:759 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [cluster-ClusterId{value='60840f0feee7e9676940005d', description='null'}-mongodb:27017] thread | io.supertokens.storage.mongodb.MongoDBLoggingAppender.doAppend(MongoDBLoggingAppender.java:136) | Execution of command with request id 34 completed successfully in 1.94 ms on connection [connectionId{localValue:1, serverValue:1}] to server mongodb:27017

    24 Apr 2021 12:32:33:760 +0000 | DEBUG | pid: 174172de-95ba-4700-8074-c196787f93fa | [cluster-ClusterId{value='60840f0feee7e9676940005d', description='null'}-mongodb:27017] thread | io.supertokens.storage.mongodb.MongoDBLoggingAppender.doAppend(MongoDBLoggingAppender.java:136) | Updating cluster description to  {type=STANDALONE, servers=[{address=mongodb:27017, type=STANDALONE, roundTripTime=3.7 ms, state=CONNECTED}]

My API is currently using supertokens-node 4.3.1, and below is the docker-compose file I use - just in case it's relevant :

    version: "2"
    services:
      supertokens-server:
        image: supertokens/supertokens-mongodb
        restart: unless-stopped
        environment:
          - MONGODB_CONNECTION_URI=mongodb://root:root@mongodb:27017
        depends_on:
          - mongodb
        ports:
          - 3567:3567
      mongodb:
        image: mongo
        restart: unless-stopped
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
          - 27017:27017
        volumes:
          - mongodb_data:/data/db
          
    volumes:
      mongodb_data:
        driver: local

**Comment by rishabhpoddar** [comment]
MongoDB only works with session management at the moment (only the session recipe). The reason the in mem db works is cause it's using an SQL database in memory. Maybe use MySQL or PostgreSQL instead of mongodb, and it should work just fine..
